//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.10 at 02:46:42 PM CST 
//


package com.dchealth.healthcard.soapclient;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ws.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ws.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Login }
     *
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     *
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Logout }
     *
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     *
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link ChangePassword }
     *
     */
    public ChangePassword createChangePassword() {
        return new ChangePassword();
    }

    /**
     * Create an instance of {@link ChangePasswordResponse }
     *
     */
    public ChangePasswordResponse createChangePasswordResponse() {
        return new ChangePasswordResponse();
    }

    /**
     * Create an instance of {@link GetAutoUpdateInfo }
     *
     */
    public GetAutoUpdateInfo createGetAutoUpdateInfo() {
        return new GetAutoUpdateInfo();
    }

    /**
     * Create an instance of {@link GetAutoUpdateInfoResponse }
     *
     */
    public GetAutoUpdateInfoResponse createGetAutoUpdateInfoResponse() {
        return new GetAutoUpdateInfoResponse();
    }

    /**
     * Create an instance of {@link GetUsersApplication }
     *
     */
    public GetUsersApplication createGetUsersApplication() {
        return new GetUsersApplication();
    }

    /**
     * Create an instance of {@link GetUsersApplicationResponse }
     *
     */
    public GetUsersApplicationResponse createGetUsersApplicationResponse() {
        return new GetUsersApplicationResponse();
    }

    /**
     * Create an instance of {@link GetServerDateTime }
     *
     */
    public GetServerDateTime createGetServerDateTime() {
        return new GetServerDateTime();
    }

    /**
     * Create an instance of {@link GetServerDateTimeResponse }
     *
     */
    public GetServerDateTimeResponse createGetServerDateTimeResponse() {
        return new GetServerDateTimeResponse();
    }

    /**
     * Create an instance of {@link DecryptToken }
     *
     */
    public DecryptToken createDecryptToken() {
        return new DecryptToken();
    }

    /**
     * Create an instance of {@link DecryptTokenResponse }
     *
     */
    public DecryptTokenResponse createDecryptTokenResponse() {
        return new DecryptTokenResponse();
    }

}
