logging:
  file: healthcard.log
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
    org.springframework.ws.client.core: debug
    org.apache.commons.logging: debug
soap:
  configs:
#    default-uri: http://sf201.frpzj.kskxs.com:8081/healthCard/services/elecHealthCardWebSevice?wsdl
    userName: GRMSDERMYY
    password: GRMSDERMYY123
    orgId: 630000000544
#    default-uri: http://localhost:8085/ws/point.wsdl
    default-uri: http://130.130.3.111:8080/healthCard/services/elecHealthCardWebSevice?wsdl
server:
  port: 8083
debug: false
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialet: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8

  devtools:
    restart:
      enabled: true
      exclude: /static/**,/public/**,/resources/**
      log-condition-evaluation-delta: true
  datasource:
    url: jdbc:h2:file:~/.h2/testdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
com:
  dchealth:
    dchealth:
      authention:
        name: Authorization
        prefix: zhao
        sceret: zhao
        expire: 1000000
        mockUser: user
      cors:
        allowedOrigins: http://localhost:8080,http://localhost:8081,http://localhost:8083,http://myweixin.tunnel.qydev.com,http://47.97.10.127:80,chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop,chrome-extension://ecjfcmddigpdlehfhdnnnhfgihkmejin
        allowedMethods: GET,POST,PUT,DELETE
        allowedHeaders: content-type,authorization
      except-urls: /api/hello,api/hello1\
        ,/swagger-ui.html,/**/*.js,/**/*.css,/**/*.png,/swagger-resources/configuration/ui,/v2/api-docs,/swagger-resources,/swagger-resources/configuration/security\
        ,/api/error,/api/wx,/wx/portal/**,/api/ws,/api/*,/favicon.ico,/api/geermu/**